//! Embedded pathfinding.cloud path definitions.

use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

/// The raw JSON bundle generated by build.rs from pathfinding.cloud YAML files.
const PATHS_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/pathfinding_paths.json"));

/// All known escalation paths, loaded once at startup.
pub static ALL_PATHS: LazyLock<Vec<EscalationPath>> =
    LazyLock::new(|| serde_json::from_str(PATHS_JSON).unwrap_or_default());

/// A privilege escalation path from pathfinding.cloud.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EscalationPath {
    pub id: String,
    pub name: String,
    pub category: EscalationCategory,
    pub description: String,
    pub recommendation: String,
    pub permissions: Vec<String>,
    pub services: Vec<String>,
}

/// Escalation category from pathfinding.cloud.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum EscalationCategory {
    SelfEscalation,
    PrincipalAccess,
    NewPassrole,
    ExistingPassrole,
    CredentialAccess,
}

impl std::fmt::Display for EscalationCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::SelfEscalation => write!(f, "self-escalation"),
            Self::PrincipalAccess => write!(f, "principal-access"),
            Self::NewPassrole => write!(f, "new-passrole"),
            Self::ExistingPassrole => write!(f, "existing-passrole"),
            Self::CredentialAccess => write!(f, "credential-access"),
        }
    }
}

impl EscalationPath {
    /// URL to the path's page on pathfinding.cloud
    pub fn url(&self) -> String {
        format!("https://www.pathfinding.cloud/paths/{}", self.id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_paths_loaded() {
        let paths = &*ALL_PATHS;
        // Should have 66 paths if fetch succeeded, 0 if offline build
        println!("Loaded {} pathfinding.cloud paths", paths.len());
        if !paths.is_empty() {
            assert!(paths.iter().any(|p| p.id == "iam-001"));
            assert!(paths.iter().any(|p| p.id == "lambda-001"));
            assert!(paths.iter().any(|p| p.id == "sts-001"));

            let iam001 = paths.iter().find(|p| p.id == "iam-001").unwrap();
            assert_eq!(iam001.category, EscalationCategory::SelfEscalation);
            assert!(iam001
                .permissions
                .contains(&"iam:CreatePolicyVersion".to_string()));
        }
    }
}
